on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.200.239.27
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            ls
            git remote add origin https://github.com/Abhiraj028/w25.1.git
            cd w25.1
            npm i
            npm run build
            npm run start